USE [master]
GO

DECLARE @dbname nvarchar(128)
SET @dbname = 'WineStoreDW'

IF EXISTS (select name from master.dbo.sysdatabases where name = @dbname)
BEGIN
	ALTER DATABASE WineStoreDW SET OFFLINE WITH ROLLBACK IMMEDIATE
	DROP DATABASE [WineStoreDW]
	
END
/****** Object:  Database [WineStoreDW]    Script Date: 9/15/2022 8:33:12 PM ******/
CREATE DATABASE [WineStoreDW]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WineStoreDW', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\WineStoreDW.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'WineStoreDW_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\WineStoreDW_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WineStoreDW].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WineStoreDW] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WineStoreDW] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WineStoreDW] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WineStoreDW] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WineStoreDW] SET ARITHABORT OFF 
GO

ALTER DATABASE [WineStoreDW] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WineStoreDW] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WineStoreDW] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WineStoreDW] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WineStoreDW] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WineStoreDW] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WineStoreDW] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WineStoreDW] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WineStoreDW] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WineStoreDW] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WineStoreDW] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WineStoreDW] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WineStoreDW] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WineStoreDW] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WineStoreDW] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WineStoreDW] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WineStoreDW] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WineStoreDW] SET RECOVERY FULL 
GO

ALTER DATABASE [WineStoreDW] SET  MULTI_USER 
GO

ALTER DATABASE [WineStoreDW] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WineStoreDW] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WineStoreDW] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WineStoreDW] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [WineStoreDW] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WineStoreDW] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [WineStoreDW] SET QUERY_STORE = OFF
GO

ALTER DATABASE [WineStoreDW] SET  READ_WRITE 
GO


