USE [master]
GO

DECLARE @dbname nvarchar(128)
SET @dbname = 'WineStore'

IF EXISTS (select name from master.dbo.sysdatabases where name = @dbname)
BEGIN
	ALTER DATABASE WineStore SET OFFLINE WITH ROLLBACK IMMEDIATE
	DROP DATABASE [WineStore]
	
END
/****** Object:  Database [WineStore]    Script Date: 9/15/2022 8:33:12 PM ******/
CREATE DATABASE [WineStore]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WineStore', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\WineStore.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'WineStore_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\WineStore_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WineStore].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WineStore] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WineStore] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WineStore] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WineStore] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WineStore] SET ARITHABORT OFF 
GO

ALTER DATABASE [WineStore] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WineStore] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WineStore] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WineStore] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WineStore] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WineStore] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WineStore] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WineStore] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WineStore] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WineStore] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WineStore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WineStore] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WineStore] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WineStore] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WineStore] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WineStore] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WineStore] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WineStore] SET RECOVERY FULL 
GO

ALTER DATABASE [WineStore] SET  MULTI_USER 
GO

ALTER DATABASE [WineStore] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WineStore] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WineStore] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WineStore] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [WineStore] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WineStore] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [WineStore] SET QUERY_STORE = OFF
GO

ALTER DATABASE [WineStore] SET  READ_WRITE 
GO


